/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMessageBox: typeof import('./src/pages/emergency/marshalling/components/AlertMessageBox.vue')['default']
    AllFloors: typeof import('./src/components/AllFloors.vue')['default']
    BlockComponent: typeof import('./src/components/BlockComponent.vue')['default']
    BuildingSelect: typeof import('./src/components/BuildingSelect.vue')['default']
    CameraWebRTC: typeof import('./src/components/CameraWebRTC.vue')['default']
    CascaderItem: typeof import('./src/components/QCascader/CascaderItem.vue')['default']
    DateRangeSelect: typeof import('./src/components/DateRangeSelect.vue')['default']
    DateSelect: typeof import('./src/components/DateSelect.vue')['default']
    DialogContact: typeof import('./src/components/Dialog/DialogContact.vue')['default']
    DialogDataRowPreview: typeof import('./src/components/Dialog/DialogDataRowPreview.vue')['default']
    DialogExportExcel: typeof import('./src/components/Dialog/DialogExportExcel.vue')['default']
    DialogFilePreview: typeof import('./src/components/Dialog/DialogFilePreview.vue')['default']
    DialogForm: typeof import('./src/components/Dialog/DialogForm.vue')['default']
    DialogImportExcel: typeof import('./src/components/Dialog/DialogImportExcel.vue')['default']
    DialogSimulationTest: typeof import('./src/components/Dialog/DialogSimulationTest.vue')['default']
    DialogUpload: typeof import('./src/components/Dialog/DialogUpload.vue')['default']
    EditableTextarea: typeof import('./src/components/editableTextarea.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    FamilyStatusComponent: typeof import('./src/pages/emergency/marshalling/components/FamilyStatusComponent.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    FireCrewCarousel: typeof import('./src/pages/emergency/marshalling/components/FireCrewCarousel.vue')['default']
    FloorsForBasicInfo: typeof import('./src/components/floorsForBasicInfo.vue')['default']
    FloorsForViewer: typeof import('./src/components/floorsForViewer.vue')['default']
    MarqueeComponent: typeof import('./src/layouts/components/MarqueeComponent.vue')['default']
    MetcHelper: typeof import('./src/layouts/components/MetcHelper.vue')['default']
    MissionList: typeof import('./src/pages/emergency/marshalling/components/MissionList.vue')['default']
    NavBarComponent: typeof import('./src/layouts/components/NavBarComponent.vue')['default']
    NoPermissionCard: typeof import('./src/components/NoPermissionCard.vue')['default']
    QCascader: typeof import('./src/components/QCascader/QCascader.vue')['default']
    RemindList: typeof import('./src/pages/emergency/marshalling/components/RemindList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SDFMViewerPeople: typeof import('./src/pages/emergency/marshalling/components/SDFMViewerPeople.vue')['default']
    SvgBtn: typeof import('./src/components/SvgBtn.vue')['default']
    SvgDropdownBtn: typeof import('./src/components/SvgDropdownBtn.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
}
