import { uid } from "quasar";

export default [
  {
    id: uid(),
    iconId: "fire_f1",
    name: "室內消防栓",
    type: "FFE_IndoorFireHydrant",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_f2",
    name: "室外消防栓",
    type: "FFE_OutdoorFireHydrant",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_f3",
    name: "自動撒水",
    type: "FFE_AutomaticSprinklerSystem",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_f4",
    name: "泡沫",
    type: "FFE_FoamFireExtinguisher",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_f5",
    name: "水霧",
    type: "FFE_WaterMistSystem",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_f6",
    name: "惰性氣體",
    type: "FFE_InertGasSystem",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_f7",
    name: "鹵化烴",
    type: "FFE_HalohydrocarbonSystem",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_f8",
    name: "乾粉",
    type: "FFE_DryPowderSystem",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_f9",
    name: "加壓送水裝置",
    type: "PressurizedWater",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
    ],
    action: [
      { value: "0", label: "停止", color: "#bdbbbb" },
      { value: "1", label: "啟動", color: "#e31717" },
    ],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_a1",
    name: "火警授信總機",
    type: "AE_FireDetectorCentralControl",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_a2",
    name: "偵煙式探測器",
    type: "AE_SmokeDetector",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_a3",
    name: "光電式分離型探測器",
    type: "AE_PhotoelectricSeparationDetector",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_a4",
    name: "感熱式探測器",
    type: "AE_ThermalDetector",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_a5",
    name: "火焰式探測器",
    type: "AE_FlameDetector",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_a6",
    name: "瓦斯漏氣檢知器",
    type: "AE_TileLeakDetector",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_a7",
    name: "火警發信機",
    type: "AE_ManualAlarmDevice",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_a8",
    name: "緊急廣播設備",
    type: "AE_EmergencyBroadcastDevice",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_fp1",
    name: "防火捲門",
    type: "FPE_RollingFireDoor",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
    ],
    action: [{ value: "0", label: "關", color: "#e31717" }],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_fp2",
    name: "防火門",
    type: "FPE_FireDoor",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
    ],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r1",
    name: "防煙垂壁",
    type: "SPE_SmokeBarrier",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
    ],
    action: [
      { value: "0", label: "關", color: "#bdbbbb" },
      { value: "1", label: "開", color: "#e31717" },
    ],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r2",
    name: "自然排煙窗",
    type: "SPE_NaturalSmokeExhaustWindow",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
      { value: "2", color: "#54e823" },
    ],
    action: [
      { value: "0", label: "關", color: "#bdbbbb" },
      { value: "1", label: "開", color: "#e31717" },
      { value: "2", label: "停止", color: "#e31717" },
    ],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r3",
    name: "排煙機",
    type: "RE_SmokeExtractionDevice",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
    ],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r4",
    name: "排煙口",
    type: "RE_SmokeOutlet",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
    ],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r5",
    name: "特別安全梯排煙口進風口",
    type: "SpecialSmokeOutlet",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
    ],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r6",
    name: "防火閘門",
    type: "RE_SmokeOutlet",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#54e823" },
    ],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r7",
    name: "連結送水口",
    type: "ConnectWaterOutlet",
    status: [{ value: "0", color: "#bdbbbb" }],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r8",
    name: "緊急電源插座",
    type: "RE_EmergencyPowerSocket",
    status: [{ value: "0", color: "#bdbbbb" }],
    // hasAddress: false,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_r9",
    name: "無線電通信輔助",
    type: "RE_RadioEquipment",
    status: [{ value: "0", color: "#bdbbbb" }],
    // hasAddress: false,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_c1",
    name: "緊急升降機",
    type: "CE_Elevator",
    status: [{ value: "0", color: "#bdbbbb" }],
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_s1",
    name: "避難引導燈具",
    type: "SRE_EscapeGuideLights",
    activeColor: "#54e823",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_s2",
    name: "緊急照明燈",
    type: "SRE_EmergencyLighting",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_o1",
    name: "電燈",
    type: "OE_ElectricLight",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_o2",
    name: "緊急門鎖",
    type: "OE_EmergencyDoorLock",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_o3",
    name: "監視攝影機",
    type: "OE_CCTV",
    activeColor: "#54e823",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_o4",
    name: "PLC",
    type: "OE_ProgrammableLogicController",
    status: [{ value: "0", color: "#bdbbbb" }],
    // hasAddress: false,
  },
  {
    id: uid(),
    iconId: "fire_p1",
    name: "緊急電話",
    type: "EmergencyCall",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#e31717" },
    ],
    // hasAddress: false,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_p2",
    name: "高壓氣體容器儲存場所",
    type: "HighPressurePlace",
    status: [{ value: "0", color: "#bdbbbb" }],
    // hasAddress: false,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_p3",
    name: "公共危險物品儲存場所",
    type: "PublicDangerousPlace",
    status: [{ value: "0", color: "#bdbbbb" }],
    // hasAddress: false,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_p4",
    name: "空調",
    type: "CE_AirConditioning",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#e31717" },
    ],
    trigger: 1,
    // hasAddress: true,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_p5",
    name: "消防專用蓄水池",
    type: "RE_FireReservoir",
    activeColor: "#e31717",
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_p7",
    name: "已定位",
    type: "PeopleReady",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#e31717" },
    ],
    // hasAddress: false,
    useType: 1,
  },
  {
    id: uid(),
    iconId: "fire_p8",
    name: "醫療設備",
    type: "medical",
    status: [
      { value: "0", color: "#bdbbbb" },
      { value: "1", color: "#e31717" },
    ],
    // hasAddress: false,
    useType: 1,
  },
];
